# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Release

on:
  push:
    branches: [ master ]
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Get tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set pom version with TAG value
      run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

    - name: Git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit files
      run: |
        git commit -m "[Release][${{ steps.get_version.outputs.VERSION }}] Pom version change" pom.xml

    - name: Update tag
      run: |
        git tag ${{ steps.get_version.outputs.VERSION }}-RELEASE

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn install
    - name: Publish maven artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/txuselo -Dtoken=${GITHUB_TOKEN}
